### ISSUE TITLE
【项目】 Slack <-> wechat <-> github <-> zoom (message syncing)

### ISSUE THREAD

**Issue by robturtle** [tech-gamers/ideas#1]
## tech requirements
You do *NOT* necessarily need to know all of them. You do *NOT* necessarily need to know them beforehand.

- Slack Integration
- Wechat integration/plugin/microapp (whatever it called, whatever can implement it)
- GitHub API
- Zoom API

The goal is
1. Slack/GitHub should be the very end of the data flow (structural/hierarchical/topic-focusing separations)
2. WeChat group should be the very start of the data flow. (Since this is the most convenient way to get inputs)

## slack side
- [ ] push announcement to wechat group
- [ ] push polls to wechat group

Example of slack text-based polls:
![image](https://user-images.githubusercontent.com/3524125/87393960-dee1de00-c563-11ea-903a-b7ba08a267eb.png)

## wechat side
- [ ] push ideas to here (Github issues)
- [ ] push polls to slack
- [ ] in-group wechat bot
  - [ ] welcome new members
  - [ ] command executor

## zoom side
- [ ] post livestream/meeting notification to slack/wechat

**Comment by wangtjwork** [comment]
Interesting. I know there's WeChat bots out there but don't really know how it's implemented.

**Comment by robturtle** [comment]
@wangtjwork Join #side-projects-incubator channel and let's discuss more!
